### ISSUE TITLE
Explore Argobots + Charm++ for Xeon Phi

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#65]
Argobots is an implementation of a new threading/tasking framework that can be used in Charm++ with great potential for many cores, e.g., Xeon Phi. More info at
- http://charm.cs.illinois.edu/workshops/charmWorkshop2015/program.php
- http://www.argobots.org/
- https://github.com/pmodels/argobots

**Comment by rspavel** [comment]
A quick git grep of the 6.8 beta and latest 6.7.x using git grep -i ARGO gives nothing related to argobots. And it looks like the last commit the argobots branch(es) (which haven't had a commit pushed since Jan 2016) have in common with the 6.8 is from Thu Jul 17 18:38:38 2014 -0400

So I think it is safe to say that this is almost purely a research project and is unlikely to work with any recent charm build. We can inquire further at the workshop but I think it is safe to assume this isn't a viable option.

**Comment by jbakosi** [comment]
Yes, argobots was and most likely remains a research project and not (yet) part of mainline Charm++. However, when I first heard about it at the 2015 Charm++ Workshop I was told that though it is experimental, it already worked at the time with Charm++. Since they still have not merged to master, you are most likely correct that it probably not yet intended for production and remains a research project. But so are we... It will nevertheless be a good thing to ask about it and see if we should further explore.

**Comment by jbakosi** [comment]
After consulting the Charm++ developers, I don't think this is worth pursuing. The most important features of user-level threads and asynchronous node-level thread scheduling are already available in Charm++ or can be accessed via other existing abstractions. Plus argobots integration in Charm++ collecting dust at this point.
