### ISSUE TITLE
Use Ubuntu's pegtl-dev

### ISSUE THREAD

**Issue by junghans** [quinoacomputing/quinoa#91]

**Comment by junghans** [comment]
pegtl-1.3.1 added to Gentoo in gentoo/gentoo@5e790fedf0086cbcd5f1f27cffb062d8e1a28552

**Comment by jbakosi** [comment]
Started porting to new [PEGTL](https://github.com/ColinH/PEGTL). This is on branch `pegtl`.

Progress so far:
- The `tpl/CMakeLists.txt` as well as `cmake/TPLs.cmake` now find the system-wide PEGTL. Tested on debian installing the [libpegtl-dev](https://packages.debian.org/search?keywords=pegtl&searchon=names&suite=testing&section=all) package.
- Ported [`kw::keyword`](http://quinoacomputing.github.io/quinoa/structkw_1_1keyword.html) and the definition of all individual keywords to use the new `tk::keyword`.

Next on my list is `apply()` and revamping pegtl actions, also discussed below.

For background and documentation, I paste here a part of @d-frey's initial comments from my conversation with the PEGTL developers over a year ago, which gives a starting point for porting:

**Comment by jbakosi** [comment]
After much email exchange with the PEGTL developers, who helped me tremendously during converting to the new PEGTL, it seems like now I have been able to get to a point where I can say with some confidence that porting to the new PEGTL will succeed.

At this point, 16a45ed8e3a, meshconv, unittest, numdiff, and walker successfully builds with the new PEGTL and all of walker's regression tests pass. (Though the grammar is not fully unit-tested, of all tools we build, walker has the most complex grammar.) Converting the inciter and rngtest should not be a big deal.

This is only tested using clang.

**Comment by jbakosi** [comment]
Almost done, see f6d42677abc. The final step is to figure out why gcc would not build this.

**Comment by jbakosi** [comment]
This is done. Will create a pull-request for it shortly.

Converting to the new PEGTL API works on my (debian) workstation with clang (3.8), gcc (6.3), and intel (17.0.1), all with openmpi 1.10.2. Also tested on one of the TeamCity build agents which has a spack-installed openmpi-2.0.1-gcc-4.8.5. Note that if I pull in debian's [libopenmpi2](https://packages.debian.org/stretch/libopenmpi2), which is the default openmpi on debian/testing at this time, which has openmpi 2.0.2, Zoltan (in Trilinos) fails all inciter's regression tests that use a nonzero virtualization (via the `-u` command line argument). I did not investigate this further because openmpi 2.0.1 works fine, but here is a trace for documentation:

```
Zoltan_Malloc (from /home/jbakosi/code/quinoa/tpl/src/trilinos/packages/zoltan/src/all/all_allo.c,194) No space on proc 0 - number of bytes requested = 18446744068085289472
[0] Zoltan ERROR in Zoltan_Invert_Lists (line 250 of /home/jbakosi/code/quinoa/tpl/src/trilinos/packages/zoltan/src/lb/lb_invert.c):  Insufficient memory.
[0] Zoltan ERROR in Zoltan_LB (line 582 of /home/jbakosi/code/quinoa/tpl/src/trilinos/packages/zoltan/src/lb/lb_balance.c):  Error building return arguments; -2 returned by 
Zoltan_Compute_Destinations                                                       
                                                                                  
terminate called after throwing an instance of 'std::runtime_error'               
  what():  0: /home/jbakosi/code/quinoa/tpl/install/gnu-x86_64/include/Zoltan2_AlgZoltan.hpp,380
0: error: Zoltan LB_Partition
```

It seems like an integer overflow inside Zoltan. I don't think this is a major issue at this point as openmpi 2.0.1 and below work fine and perhaps newer Trilinos versions might already have a fix for Zoltan for this.

This branch not only converts PEGTL grammar and parser code to PEGTL 1.3 (from the ancient 0.32), but also updates our own PEGTL version (pulled in via [git subtree](http://quinoacomputing.github.io/quinoa/subtree.html), in tpl/src/pegtl). This allows providing the correct version of PEGTL if unavailable system-wide. As always forcing our own PEGTL (instead of the system's) can be done via the -DNO_SYSTEM_PEGTL=true cmake argument of the TPL build.

Note that there is no mechanism at this time to query the PEGTL version. As a result, if we detect a system-wide one we don't know if it is a version that we is correct for us. However, the PEGTL developers are already working on adding versioning and a query mechanism to future versions.

**Comment by jbakosi** [comment]
Done. See https://github.com/quinoacomputing/quinoa/pull/94.
